// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPR1p-S664cM_D__3ufMFJzs5d5XLtWZ8',
    appId: '1:788774532481:web:a2b77f55aec73af24c2480',
    messagingSenderId: '788774532481',
    projectId: 'prubita',
    authDomain: 'prubita.firebaseapp.com',
    storageBucket: 'prubita.firebasestorage.app',
    measurementId: 'G-BS3Q63238D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcAqe1JEzCSMvtpEHurjZCmmL3Dz8SW0',
    appId: '1:788774532481:android:dcb04308625403b14c2480',
    messagingSenderId: '788774532481',
    projectId: 'prubita',
    storageBucket: 'prubita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqUYR8XRxsU8nxbn7hmxWu1HCLBARPGY',
    appId: '1:788774532481:ios:6311dca7577617704c2480',
    messagingSenderId: '788774532481',
    projectId: 'prubita',
    storageBucket: 'prubita.firebasestorage.app',
    iosBundleId: 'com.example.guia07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqUYR8XRxsU8nxbn7hmxWu1HCLBARPGY',
    appId: '1:788774532481:ios:6311dca7577617704c2480',
    messagingSenderId: '788774532481',
    projectId: 'prubita',
    storageBucket: 'prubita.firebasestorage.app',
    iosBundleId: 'com.example.guia07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPR1p-S664cM_D__3ufMFJzs5d5XLtWZ8',
    appId: '1:788774532481:web:0e8af40eb94ea8694c2480',
    messagingSenderId: '788774532481',
    projectId: 'prubita',
    authDomain: 'prubita.firebaseapp.com',
    storageBucket: 'prubita.firebasestorage.app',
    measurementId: 'G-SCLW09Q8BT',
  );
}
